"""created and tested relalationships with fake data

Revision ID: 3113e09cb53b
Revises: c25a218c05c9
Create Date: 2024-02-18 15:10:53.226005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3113e09cb53b'
down_revision: Union[str, None] = 'c25a218c05c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
